# End-to-end offline demonstration in a temporary directory, never the real catalog.
source('scripts/load.R')
root <- tempfile('agents-demo-'); dir.create(root)
db <- new_db()
proposals <- observe_discover(db,1,fixture_search,fixture_fetch,'demo-discovery')
for(p in proposals) write_proposal(p,file.path(root,'proposals'))
db <- curate_proposals(db,read_proposals(file.path(root,'proposals')),fixture_extract)
stopifnot(nrow(db$calls)==1)
db$calls$fecha_cierre <- '2026-12-01'
proposals <- observe_monitor(db,fetcher=fixture_fetch,run_id='demo-monitor',force=TRUE)
for(p in proposals) write_proposal(p,file.path(root,'proposals'))
db <- curate_proposals(db,read_proposals(file.path(root,'proposals')),fixture_extract)
stopifnot(db$calls$fecha_cierre=='2026-12-15',nrow(db$agent_decisions)==2)
stopifnot(identical(db,curate_proposals(db,read_proposals(file.path(root,'proposals')),fixture_extract)))
save_db(db,root)
stopifnot(identical(db,load_db(file.path(root,'canonical'))))
cat('DEMO OK: descubrimiento -> cola -> curaduría -> vigilancia -> actualización.\n')
cat('Sin Internet, sin API, sin cambios en el catálogo real.\n')
cat('Resultado temporal:',root,'\n')
